# Generated by Django 6.0.2 on 2026-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
