# Generated by Django 6.0.2 on 2026-02-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submission_ai_feedback_submission_ai_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
