# Generated by Django 6.0.2 on 2026-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_submission_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.IntegerField(default=10),
        ),
    ]
